# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - '3306:3306'
    volumes:
    - './mysql:/var/lib/mysql'
#    environment:
#    - 'MYSQL_ROOT_PASSWORD=black-malang-cow'